meta:
  url: https://hiroppy.github.io/fusuma/themes
  title: introducing themes
  description: fusuma provides some themes
  siteName: hiroppy.me
  sns: ['twitter']
slide:
  ui:
  code:
    plugins: []
    theme: default
build:
  useCache: false
