meta:
  url:
  title:
  description:
  siteName:
  sns: ['twitter']
slide:
  ui:
  code:
    # https://prismjs.com/
    plugins: []
    theme: default # coy | dark | funky | okaidia | solarizedlight | tomorrow | twilight
